encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry_page, name="entry_page"),
    path("search_results", views.search_results, name="search_results"),
    path("create_new_page", views.CreatePage.as_view(), name="create_new_page"),
    path("wiki/<str:title>/edit_page", views.EditPage.as_view(), name="edit_page"),
    path("random_page", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import redirect
from django.contrib import messages
import markdown2
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
    

def entry_page(request, title):
    entries = set(util.list_entries())
    if title not in entries:
        raise Http404()  
    page_content = markdown2.markdown(util.get_entry(title))   
    return render(request, "encyclopedia/entry_page.html", {
        "title": title,
        "page_content": page_content
    })

def search_results(request):
    query = request.GET.get('q', '')
    entries = set(util.list_entries())
    if query in entries:
        return redirect('wiki:entry_page', query)
    else:
        potential_matches = [title for title in entries if query in title]
        return render(request, "encyclopedia/search_results.html", {
        "query": query,
        "potential_matches": potential_matches
    })

def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return redirect('wiki:entry_page', random_entry)


class CreatePage(View):

    def get(self, request):
        return render(request, "encyclopedia/create_new_page.html")
        
    def post(self, request):
        title = request.POST.get("title")
        entries = set(util.list_entries())
        if title in entries:
            messages.error(request, "The Page you are trying to create already exist. You can't overwrite it (Please try to \"Edit Page\" to modify it).")
            return render(request, "encyclopedia/create_new_page.html")
        page_content = request.POST.get("page_content")
        util.save_entry(title, page_content)
        return redirect('wiki:entry_page', title)


class EditPage(View):

    def get(self, request, title):
        page_content = util.get_entry(title)   
        return render(request, "encyclopedia/edit_page.html",  {
        "title": title,
        "page_content":page_content
    })
        
    def post(self, request, title):
        page_content = request.POST.get("page_content")
        util.save_entry(title, page_content)
        return redirect('wiki:entry_page', title)

encyclopedia/templates/encyclopedia/create_new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new page
{% endblock %}

{% block body %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post" action="{% url 'wiki:create_new_page' %}">
  {% csrf_token %}
    <label for="title">Title:</label>
    <br>
    <input name="title" placeholder="new title">
    <br>
    <label for="page_content">Page content:</label>
    <br>
    <textarea name="page_content" placeholder="Page content"></textarea>
    <br>
    <input type="submit" value="Create">
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page: {{ title }}
{% endblock %}

{% block body %}
<h3>Edit Page: {{ title }}</h3>
    <form method="post" action="{% url 'wiki:edit_page' title%}">
    {% csrf_token %}
        <br>
        <label for="page_content">Page content:</label>
        <br>
        <textarea name="page_content">{{ page_content }}</textarea>
        <br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title|safe}}
{% endblock %}

{% block nav %}
<br>
<div>
    <a href="{% url 'wiki:edit_page' title %}">Edit Page</a>
</div>
{% endblock %}

{% block body %}
    {{page_content|safe}}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for title in entries %}
        <li><a href="{% url 'wiki:entry_page' title %}">{{ title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search_results' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create_new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ query }} search results
{% endblock %}

{% block body %}
<ul>
    <h3>"{{ query }}" search results:</h3>
    {% for match in potential_matches %}
    <li><a href="{% url 'wiki:entry_page' match %}">{{ match }}</a></li>
    {% endfor %}
</ul> 
{% endblock %}